import base64

# ================= KONFIGURASI =================
# Anda dapat mengubah atau memasukkan kembali API / Token Anda di sini:
TOKEN = "8426670545:"
NEWS_API_KEY = "rNcChsGOPUdrSX"
# ===============================================

_enc_payload = (
    b'import logging\nimport requests\nimport pandas as pd\nimport math\nimport '
    b'io\nimport matplotlib\nmatplotlib.use(\'Agg\')\nimport matplotlib.pyplot '
    b'as plt\nimport matplotlib.dates as mdates\nfrom telegram import Update\n'
    b'from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes'
    b'\n\nREAL_BROWSER_HEADERS = {\n    \'User-Agent\': \'Mozilla/5.0 (Windows '
    b'NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
    b'Chrome/124.0.0.0 Safari/537.36\',\n    \'Accept\': \'text/html,'
    b'application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,'
    b'image/apng,*/*;q=0.8\',\n    \'Accept-Language\': \'en-US,en;q=0.9,id;q=0'
    b'.8\',\n    \'Accept-Encoding\': \'gzip, deflate, br\',\n    \'Connection'
    b'\': \'keep-alive\'\n}\n\nlogging.basicConfig(format=\'%(asctime)s - '
    b'%(name)s - %(levelname)s - %(message)s\', level=logging.INFO)\n\nasync '
    b'def start(update: Update, context: ContextTypes.DEFAULT_TYPE):\n    '
    b'welcome_msg = (\n        "\\U0001f916 <b>BOT ANALISA FINANSIAL (TF '
    b'6H)</b>\\n"\n        "━━━━━━━━━━━━━━━━━━━\\n"\n        "Akses analisa '
    b'teknikal institusional, setup entry presisi, dan berita pasar menggunakan'
    b' data Binance.\\n\\n"\n        "📌 <b>Cara Penggunaan:</b>\\n"\n        "• '
    b'Kripto / Komoditas: <code>/p btc</code> atau <code>/p paxg</code>\\n"\n '
    b'       "• Saham / ETF: <code>/stock aaplb</code>\\n"\n        "• Daftar '
    b'Menu: <code>/list</code>\\n\\n"\n        "<i>By arifrfza (@vuxoz)</i>"\n    '
    b')\n    await update.message.reply_text(welcome_msg, parse_mode="HTML")\n\n'
    b'async def list_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):\n'
    b'    list_msg = (\n        "\\U0001f4cb <b>DIREKTORI MENU & INSTRUMEN (TF '
    b'6H)</b>\\n"\n        "━━━━━━━━━━━━━━━━━━━\\n\\n"\n        "🔥 <b>KEMAMPUAN '
    b'UTAMA ANALISA BINANCE:</b>\\n"\n        "<i>Bot ini mampu dan dapat '
    b'menganalisa <b>SEMUA</b> koin kripto, token, saham global, ETF, maupun '
    b'komoditas apa pun yang aktif dan tersedia di Binance Spot Market secara '
    b'real-time! Anda bebas mengetik simbol apa saja.</i>\\n\\n"\n        "🥇 '
    b'<b>KOMODITAS & LOGAM MULIA</b>\\n"\n        "• <code>/p paxg</code> — PAX '
    b'Gold (Emas Fisik)\\n"\n        "• <code>/p gold</code> — Alternatif '
    b'Emas\\n\\n"\n        "🪙 <b>CONTOH KRIPTO POPULER</b>\\n"\n        "• '
    b'<code>/p btc</code> — Bitcoin\\n"\n        "• <code>/p eth</code> — '
    b'Ethereum\\n"\n        "• <code>/p sol</code> — Solana\\n"\n        "• '
    b'<code>/p bnb</code> — Binance Coin\\n"\n        "• <code>/p xrp</code> '
    b'— Ripple\\n"\n        "• <code>/p doge</code> — Dogecoin\\n"\n        "• '
    b'<code>/p ada</code> — Cardano\\n"\n        "• <code>/p avax</code> — '
    b'Avalanche\\n\\n"\n        "📊 <b>CONTOH ETF & SAHAM GLOBAL (Binance '
    b'Spot)</b>\\n"\n        "• <code>/stock qqqb</code> — Invesco QQQ '
    b'(Nasdaq)\\n"\n        "• <code>/stock spyb</code> — SPDR S&P 500\\n"\n    '
    b'    "• <code>/stock aaplb</code> — Apple Inc.\\n"\n        "• '
    b'<code>/stock tslab</code> — Tesla Inc.\\n"\n        "• <code>/stock '
    b'nvdab</code> — NVIDIA Corp.\\n\\n"\n        "━━━━━━━━━━━━━━━━━━━\\n"\n    '
    b'    "⚠️ <b>Catatan Penting:</b>\\n"\n        "• Gunakan <code>/p '
    b'&lt;simbol_koin&gt;</code> untuk semua koin/komoditas yang ada di '
    b'Binance.\\n"\n        "• Gunakan <code>/stock &lt;simbol&gt;b</code> '
    b'untuk saham/ETF yang terdaftar di Binance Spot.\\n"\n        "<i>By '
    b'arifrfza (@vuxoz)</i>"\n    )\n    await update.message.reply_text(list_msg'
    b', parse_mode="HTML")\n\ndef format_price(val):\n    if pd.isna(val): '
    b'return "$0.00"\n    if val < 0.001: return f"${val:,.8f}"\n    if val < 1:'
    b' return f"${val:,.4f}"\n    return f"${val:,.2f}"\n\ndef generate_chart(df'
    b', display_name, entry_long, entry_short, tp1_long, tp2_long, sl_long, '
    b'sl_short, tp1_short, tp2_short):\n    plt.figure(figsize=(12, 6.75))\n   '
    b' if not pd.api.types.is_datetime64_any_dtype(df.index):\n        df.index'
    b' = pd.to_datetime(df.index)\n        \n    colors = [\'#26a69a\' if c >= '
    b'o else \'#ef5350\' for c, o in zip(df[\'Close\'], df[\'Open\'])]\n    '
    b'plt.vlines(x=df.index, ymin=df[\'Low\'], ymax=df[\'High\'], color=colors, '
    b'linewidth=1.5)\n    \n    bottoms = [min(c, o) for c, o in zip(df[\'Close'
    b'\'], df[\'Open\'])]\n    heights = [abs(c - o) for c, o in zip(df[\'Close'
    b'\'], df[\'Open\'])]\n    heights = [max(h, df[\'Close\'].iloc[i] * 0.001) '
    b'for i, h in enumerate(heights)]\n    \n    plt.bar(x=df.index, '
    b'height=heights, bottom=bottoms, color=colors, width=0.18)\n    \n    '
    b'plt.axhline(y=tp2_long, color=\'#006400\', linestyle=\'-\', '
    b'linewidth=1.5, alpha=0.7)\n    plt.axhline(y=tp1_long, color=\'#2ca02c\', '
    b'linestyle=\'-.\', linewidth=1.5, alpha=0.7)\n    plt.axhline(y=entry_long,'
    b' color=\'blue\', linestyle=\'--\', linewidth=1.5, alpha=0.8)\n    '
    b'plt.axhline(y=sl_long, color=\'#ff7f0e\', linestyle=\':\', linewidth=1.5,'
    b' alpha=0.7)\n    \n    plt.axhline(y=entry_short, color=\'purple\', '
    b'linestyle=\'--\', linewidth=1.5, alpha=0.8)\n    plt.axhline(y=tp1_short,'
    b' color=\'#d62728\', linestyle=\'-.\', linewidth=1.5, alpha=0.7)\n    '
    b'plt.axhline(y=tp2_short, color=\'#8b0000\', linestyle=\'-\', '
    b'linewidth=1.5, alpha=0.7)\n    \n    plt.title(f\'Grafik TF 6H: '
    b'{display_name}\', fontsize=14, fontweight=\'bold\', pad=15)\n    '
    b'plt.ylabel(\'Harga (USD)\', fontsize=11)\n    plt.grid(True, '
    b'linestyle=\'--\', alpha=0.3)\n    plt.gca().xaxis.set_major_formatter('
    b'mdates.DateFormatter(\'%d %b %H:%M\'))\n    plt.xticks(rotation=30, '
    b'ha=\'right\', fontsize=9)\n    plt.tight_layout(pad=1.0)\n    \n    buf = '
    b'io.BytesIO()\n    plt.savefig(buf, format=\'png\', dpi=100, '
    b'bbox_inches=\'tight\')\n    buf.seek(0)\n    plt.close()\n    return buf\n'
    b'\ndef fetch_latest_news(symbol_query):\n    try:\n        clean_sym = '
    b'symbol_query.replace("b", "").upper()\n        url = '
    b'f"https://api.marketaux.com/v1/news/all?symbols={clean_sym}&filter_entities=true&limit=2&api_token={NEWS_API_KEY}"\n'
    b'        res = requests.get(url, timeout=5)\n        if res.status_code == '
    b'200:\n            articles = res.json().get("data", [])\n            if '
    b'articles:\n                news_text = "📰 <b>Berita Terbaru:</b>\\n"\n    '
    b'            for art in articles[:2]:\n                    title = '
    b'art.get("title", "Tanpa Judul")\n                    link = art.get("url"'
    b', "#")\n                    news_text += f"• <a href=\'{link}\'>{title}</a>'
    b'\\n"\n                return news_text\n    except Exception as e:\n    '
    b'    logging.error(f"Gagal memuat berita: {e}")\n    return "📰 '
    b'<i>Berita terbaru belum tersedia.</i>"\n\ndef '
    b'calculate_analysis_and_format_report(df, display_name, raw_symbol):\n    '
    b'try:\n        current_price = float(df[\'Close\'].iloc[-1])\n        '
    b'prev_close = float(df[\'Close\'].iloc[-2]) if len(df) > 1 else '
    b'current_price\n        change = current_price - prev_close\n        '
    b'change_pct = (change / prev_close) * 100 if prev_close != 0 else 0\n    '
    b'    \n        delta = df[\'Close\'].diff()\n        gain = '
    b'(delta.where(delta > 0, 0)).rolling(14).mean()\n        loss = '
    b'(-delta.where(delta < 0, 0)).rolling(14).mean()\n        rsi = 100 - (100 '
    b'/ (1 + (gain / loss))).iloc[-1]\n        rsi_status = "Overbought ⚠️" if '
    b'rsi >= 70 else ("Oversold 🟢" if rsi <= 30 else "Netral ⚖️")\n\n        '
    b'ema_20 = float(df[\'Close\'].ewm(span=20, adjust=False).mean().iloc[-1])'
    b'\n        ema_50 = float(df[\'Close\'].ewm(span=50, adjust=False).mean()'
    b'.iloc[-1])\n        trend_bias = "Bullish 🚀" if current_price > ema_20 > '
    b'ema_50 else ("Bearish 📉" if current_price < ema_20 < ema_50 else '
    b'"Sideways ⚖️")\n\n        true_range = pd.concat([df[\'High\'] - '
    b'df[\'Low\'], (df[\'High\'] - df[\'Close\'].shift()).abs(), (df[\'Low\'] '
    b'- df[\'Close\'].shift()).abs()], axis=1).max(axis=1)\n        atr_14 = '
    b'float(true_range.rolling(14).mean().iloc[-1]) or (current_price * '
    b'0.015)\n\n        sma_20 = df[\'Close\'].rolling(window=20).mean()\n       '
    b' std_20 = df[\'Close\'].rolling(window=20).std()\n        lower_band = '
    b'float((sma_20 - (std_20 * 2)).iloc[-1])\n        upper_band = '
    b'float((sma_20 + (std_20 * 2)).iloc[-1])\n\n        recent_low = '
    b'float(df[\'Low\'].tail(10).min())\n        recent_high = '
    b'float(df[\'High\'].tail(10).max())\n\n        entry_long = round(max('
    b'recent_low, min(current_price, ema_20, lower_band if not '
    b'math.isnan(lower_band) else current_price)), 4)\n        sl_long = '
    b'round(entry_long - (atr_14 * 1.5), 4)\n        risk_long = entry_long - '
    b'sl_long\n        tp1_long = round(entry_long + (risk_long * 1.6), 4)\n   '
    b'     tp2_long = round(entry_long + (risk_long * 2.8), 4)\n        '
    b'reason_long = f"Swing Low ({format_price(recent_low)}), EMA 20 & '
    b'Bollinger Lower."\n\n        entry_short = round(min(recent_high, '
    b'max(current_price, ema_20, upper_band if not math.isnan(upper_band) else '
    b'current_price)), 4)\n        sl_short = round(entry_short + (atr_14 * '
    b'1.5), 4)\n        risk_short = sl_short - entry_short\n        tp1_short '
    b'= round(max(0.00000001, entry_short - (risk_short * 1.6)), 4)\n        '
    b'tp2_short = round(max(0.00000001, entry_short - (risk_short * 2.8)), '
    b'4)\n        reason_short = f"Swing High ({format_price(recent_high)}), '
    b'EMA 20 & Bollinger Upper."\n\n        news_section = '
    b'fetch_latest_news(raw_symbol)\n\n        sign = "+" if change >= 0 else '
    b'""\n        emoji = "📈" if change >= 0 else "📉"\n        \n        report'
    b' = (\n            f"{emoji} <b>ANALISA TF 6H: {display_name}</b>\\n"\n     '
    b'       f"━━━━━━━━━━━━━━━━━━━\\n"\n            f"💰 <b>Harga:</b> '
    b'{format_price(current_price)} ({sign}{change_pct:.2f}%)\\n"\n           '
    b' f"🧭 <b>Tren:</b> {trend_bias} | <b>RSI:</b> {rsi:.2f} ({rsi_status})\\n"\n'
    b'            f"━━━━━━━━━━━━━━━━━━━\\n"\n            f"🟢 <b>LONG (BUY '
    b'LIMIT)</b>\\n"\n            f"• Entry: {format_price(entry_long)} | SL: '
    b'{format_price(sl_long)}\\n"\n            f"• TP1: '
    b'{format_price(tp1_long)} | TP2: {format_price(tp2_long)}\\n"\n          '
    b'  f"💡 <i>Alasan: {reason_long}</i>\\n"\n            f"━━━━━━━━━━━━━━━━━━━'
    b'\\n"\n            f"🔴 <b>SHORT (SELL LIMIT)</b>\\n"\n            f"• '
    b'Entry: {format_price(entry_short)} | SL: {format_price(sl_short)}\\n"\n'
    b'            f"• TP1: {format_price(tp1_short)} | TP2: '
    b'{format_price(tp2_short)}\\n"\n            f"💡 <i>Alasan: '
    b'{reason_short}</i>\\n"\n            f"━━━━━━━━━━━━━━━━━━━\\n"\n          '
    b'  f"{news_section}\\n"\n            f"<i>By arifrfza (@vuxoz)</i>"\n    '
    b'    )\n        return report, entry_long, entry_short, tp1_long, '
    b'tp2_long, sl_long, sl_short, tp1_short, tp2_short\n    except Exception '
    b'as e:\n        logging.error(f"Error kalkulasi: {e}")\n        return '
    b'"⚠️ Terjadi kesalahan saat memproses kalkulasi.", 0, 0, 0, 0, 0, 0, 0, 0\n\n'
    b'async def fetch_binance_data(symbol):\n    try:\n        clean_symbol = '
    b'symbol.upper()\n        if clean_symbol in ["GOLD", "EMAS"]:\n           '
    b' clean_symbol = "PAXG"\n            \n        if not '
    b'clean_symbol.endswith("USDT"):\n            pair = f"{clean_symbol}USDT"'
    b'\n        else:\n            pair = clean_symbol\n\n        url = '
    b'f"https://api.binance.com/api/v3/klines?symbol={pair}&interval=6h&limit=50"\n'
    b'        res = requests.get(url, headers=REAL_BROWSER_HEADERS)\n        if '
    b'res.status_code != 200:\n            return None\n            \n        '
    b'data = res.json()\n        if not isinstance(data, list) or len(data) == '
    b'0:\n            return None\n\n        df = pd.DataFrame(data, '
    b'columns=[\'ot\', \'Open\', \'High\', \'Low\', \'Close\', \'Vol\', '
    b'\'ct\', \'qav\', \'nt\', \'tbb\', \'tbq\', \'ig\'])\n        df[[\'Open\', '
    b'\'High\', \'Low\', \'Close\']] = df[[\'Open\', \'High\', \'Low\', '
    b'\'Close\']].astype(float)\n        df.index = pd.to_datetime(df[\'ot\'], '
    b'unit=\'ms\')\n        return df\n    except Exception as e:\n        '
    b'logging.error(f"Binance fetch error: {e}")\n        return None\n\nasync '
    b'def handle_request(update: Update, context: ContextTypes.DEFAULT_TYPE):\n'
    b'    if not context.args:\n        await update.message.reply_text("⚠️ '
    b'Format salah. Contoh: <code>/p btc</code> atau <code>/stock aaplb</code>"'
    b', parse_mode="HTML")\n        return\n\n    arg = context.args[0].upper()'
    b'\n    symbol = "PAXG" if arg in ["GOLD", "EMAS"] else arg\n    '
    b'display_name = f"{symbol}/USDT"\n\n    status_msg = await '
    b'update.message.reply_text(f"⏳ Menganalisa {display_name}...")\n    df = '
    b'await fetch_binance_data(symbol)\n    if df is None:\n        await '
    b'status_msg.edit_text(f"❌ Simbol <b>{symbol}</b> tidak ditemukan di '
    b'Binance Spot Market. Pastikan kodenya terdaftar aktif di bursa.", '
    b'parse_mode="HTML")\n        return\n\n    res_tuple = '
    b'calculate_analysis_and_format_report(df, display_name, symbol)\n    if '
    b'res_tuple[1] == 0:\n        await status_msg.edit_text(res_tuple[0])\n     '
    b'   return\n\n    chart_buf = generate_chart(df, display_name, '
    b'*res_tuple[1:])\n    await status_msg.delete()\n    await '
    b'update.message.reply_photo(photo=chart_buf, caption=res_tuple[0], '
    b'parse_mode="HTML")\n\ndef main():\n    app = '
    b'ApplicationBuilder().token(TOKEN).build()\n    \n    app.add_handler('
    b'CommandHandler("start", start))\n    app.add_handler('
    b'CommandHandler("list", list_cmd))\n    app.add_handler('
    b'CommandHandler("p", handle_request))\n    app.add_handler('
    b'CommandHandler("stock", handle_request))\n    \n    print("Bot berjalan '
    b'dengan stabil dan siap menganalisa seluruh instrumen Binance...")\n    '
    b'app.run_polling()\n\nif __name__ == "__main__":\n    main()\n'
)

if __name__ == "__main__":
    exec(_enc_payload.decode('utf-8'))
