import base64

# ================= KONFIGURASI =================
# Dibuat oleh arifrfza (@vuxoz)
TOKEN = "PASTE APIKEY TELEGRAM HERE"
NEWS_API_KEY = "PASTE APIKEY MARKETAUX HERE"
# ===============================================

_enc_payload = (
    b'import logging\nimport requests\nimport pandas as pd\nimport math\nimport '
    b'io\nimport matplotlib\nmatplotlib.use(\'Agg\')\nimport matplotlib.pyplot '
    b'as plt\nimport matplotlib.dates as mdates\nfrom telegram import Update\n'
    b'from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes'
    b'\n\nREAL_BROWSER_HEADERS = {\n    \'User-Agent\': \'Mozilla/5.0 (Windows '
    b'NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
    b'Chrome/124.0.0.0 Safari/537.36\',\n    \'Accept\': \'text/html,'
    b'application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,'
    b'image/apng,*/*;q=0.8\',\n    \'Accept-Language\': \'en-US,en;q=0.9,id;q=0'
    b'.8\',\n    \'Accept-Encoding\': \'gzip, deflate, br\',\n    \'Connection'
    b'\': \'keep-alive\'\n}\n\nlogging.basicConfig(format=\'%(asctime)s - '
    b'%(name)s - %(levelname)s - %(message)s\', level=logging.INFO)\n\nasync '
    b'def start(update: Update, context: ContextTypes.DEFAULT_TYPE):\n    '
    b'welcome_msg = (\n        "<b>BOT ANALISA INSTITUSIONAL ADAPTIF</b>\\n\\n"'
    b'\n        "Akses riset teknikal mendalam yang disesuaikan secara spesifik'
    b' dengan masing-masing Timeframe.\\n\\n"\n        "<b>ðŸ“Œ TATA CARA PEMILIHAN'
    b' TIMEFRAME:</b>\\n"\n        "Sertakan kode waktu di belakang perintah '
    b'analisis Anda:\\n"\n        "â€¢ <code>6h</code> â€” Timeframe 6 Jam (Swing '
    b'Pendek)\\n"\n        "â€¢ <code>12h</code> â€” Timeframe 12 Jam (Balanced '
    b'Institutional - <i>Default</i>)\\n"\n        "â€¢ <code>1d</code> â€” '
    b'Timeframe 1 Hari / Daily (Makro Tren)\\n\\n"\n        "<b>ðŸ’¡ CONTOH '
    b'PENGGUNAAN:</b>\\n"\n        "â€¢ Kripto/Komoditas: <code>/p btc 6h</code>'
    b'\\n"\n        "â€¢ Saham/ETF: <code>/stock aaplb 1d</code>\\n"\n        "â€¢ '
    b'Lihat Menu Lengkap: <code>/list</code>\\n\\n"\n        "<i>Script dibuat '
    b'oleh arifrfza (@vuxoz)</i>"\n    )\n    await update.message.reply_text('
    b'welcome_msg, parse_mode="HTML")\n\nasync def list_cmd(update: Update, '
    b'context: ContextTypes.DEFAULT_TYPE):\n    list_msg = (\n        '
    b'"<b>DIREKTORI INSTRUMEN & PANDUAN TIMEFRAME</b>\\n\\n"\n        "<i>Catatan:'
    b' Bot ini mampu menganalisa SEMUA koin kripto, token, saham global, ETF, '
    b'maupun komoditas apa pun yang aktif diperdagangkan di Binance Spot '
    b'Market secara real-time! Di bawah ini adalah 35 macam instrumen populer '
    b'sebagai contoh referensi:</i>\\n\\n"\n        "<b>ðŸ“Œ CARA MENULIS '
    b'PERINTAH:</b>\\n"\n        "Ketik kode perintah diikuti spasi dan pilihan '
    b'waktu (<code>6h</code>, <code>12h</code>, atau <code>1d</code>).\\n\\n"\n '
    b'       "<b>ðŸ¥‡ KOMODITAS & LOGAM MULIA</b>\\n"\n        "1. <code>/p paxg '
    b'12h</code> - PAX Gold (Emas Fisik)\\n"\n        "2. <code>/p gold 1d</code>'
    b' - Alternatif Emas\\n\\n"\n        "<b>ðŸª™ KRIPTO UNGGULAN & ALTCOIN</b>\\n"'
    b'\n        "3. <code>/p btc 6h</code> - Bitcoin\\n"\n        "4. '
    b'<code>/p eth 12h</code> - Ethereum\\n"\n        "5. <code>/p sol 1d</code>'
    b' - Solana\\n"\n        "6. <code>/p bnb 6h</code> - Binance Coin\\n"\n   '
    b'     "7. <code>/p xrp 12h</code> - Ripple\\n"\n        "8. <code>/p ada '
    b'1d</code> - Cardano\\n"\n        "9. <code>/p doge 6h</code> - Dogecoin\\n"'
    b'\n        "10. <code>/p avax 12h</code> - Avalanche\\n"\n        "11. '
    b'<code>/p link 1d</code> - Chainlink\\n"\n        "12. <code>/p matic '
    b'6h</code> - Polygon\\n"\n        "13. <code>/p near 12h</code> - NEAR '
    b'Protocol\\n"\n        "14. <code>/p sui 1d</code> - SUI Network\\n"\n    '
    b'    "15. <code>/p dot 6h</code> - Polkadot\\n"\n        "16. <code>/p uni '
    b'12h</code> - Uniswap\\n"\n        "17. <code>/p atom 1d</code> - Cosmos\\n"'
    b'\n        "18. <code>/p ltc 6h</code> - Litecoin\\n"\n        "19. '
    b'<code>/p apt 12h</code> - Aptos\\n"\n        "20. <code>/p arb 1d</code> - '
    b'Arbitrum\\n"\n        "21. <code>/p op 6h</code> - Optimism\\n"\n        '
    b'"22. <code>/p inj 12h</code> - Injective\\n\\n"\n        "<b>ðŸ“Š SAHAM '
    b'GLOBAL & ETF (Spot)</b>\\n"\n        "23. <code>/stock aaplb 1d</code> - '
    b'Apple Inc.\\n"\n        "24. <code>/stock tslab 6h</code> - Tesla Inc.\\n"'
    b'\n        "25. <code>/stock nvdab 12h</code> - NVIDIA Corp.\\n"\n        '
    b'"26. <code>/stock amznb 1d</code> - Amazon.com\\n"\n        "27. '
    b'<code>/stock msftb 6h</code> - Microsoft Corp.\\n"\n        "28. '
    b'<code>/stock googlb 12h</code> - Alphabet Inc. (Google)\\n"\n        '
    b'"29. <code>/stock metaab 1d</code> - Meta Platforms\\n"\n        "30. '
    b'<code>/stock nflxb 6h</code> - Netflix Inc.\\n"\n        "31. '
    b'<code>/stock microb 12h</code> - MicroStrategy\\n"\n        "32. '
    b'<code>/stock coynb 1d</code> - Coinbase Global\\n"\n        "33. '
    b'<code>/stock mstrb 6h</code> - MSTR Stock\\n"\n        "34. '
    b'<code>/stock qqqb 12h</code> - Invesco QQQ (Nasdaq ETF)\\n"\n        '
    b'"35. <code>/stock spyb 1d</code> - SPDR S&P 500 ETF\\n\\n"\n        '
    b'"<i>Script dibuat oleh arifrfza (@vuxoz)</i>"\n    )\n    await '
    b'update.message.reply_text(list_msg, parse_mode="HTML")\n\ndef '
    b'format_price(val):\n    if pd.isna(val): return "$0.00"\n    if val < '
    b'0.001: return f"${val:,.8f}"\n    if val < 1: return f"${val:,.4f}"\n    '
    b'return f"${val:,.2f}"\n\ndef generate_chart(df, display_name, timeframe, '
    b'entry_long, entry_short, tp1_long, tp2_long, sl_long, sl_short, '
    b'tp1_short, tp2_short):\n    fig, (ax1, ax2) = plt.subplots(2, 1, '
    b'figsize=(12, 8), gridspec_kw={\'height_ratios\': [3, 1]}, sharex=True)\n  '
    b'  \n    if not pd.api.types.is_datetime64_any_dtype(df.index):\n        '
    b'df.index = pd.to_datetime(df.index)\n        \n    colors = [\'#26a69a\' '
    b'if c >= o else \'#ef5350\' for c, o in zip(df[\'Close\'], df[\'Open\'])]'
    b'\n    \n    ax1.vlines(x=df.index, ymin=df[\'Low\'], ymax=df[\'High\'], '
    b'color=colors, linewidth=1.5)\n    bottoms = [min(c, o) for c, o in zip('
    b'df[\'Close\'], df[\'Open\'])]\n    heights = [max(abs(c - o), '
    b'df[\'Close\'].iloc[i] * 0.001) for i, (c, o) in enumerate(zip(df[\'Close'
    b'\'], df[\'Open\']))]\n    ax1.bar(x=df.index, height=heights, '
    b'bottom=bottoms, color=colors, width=0.35)\n    \n    ax1.axhline(y=tp2_long'
    b', color=\'#006400\', linestyle=\'-\', linewidth=1.5, alpha=0.7)\n    '
    b'ax1.axhline(y=tp1_long, color=\'#2ca02c\', linestyle=\'-.\', '
    b'linewidth=1.5, alpha=0.7)\n    ax1.axhline(y=entry_long, color=\'blue\', '
    b'linestyle=\'--\', linewidth=1.5, alpha=0.8)\n    ax1.axhline(y=sl_long, '
    b'color=\'#ff7f0e\', linestyle=\':\', linewidth=1.5, alpha=0.7)\n    \n    '
    b'ax1.axhline(y=entry_short, color=\'purple\', linestyle=\'--\', '
    b'linewidth=1.5, alpha=0.8)\n    ax1.axhline(y=tp1_short, color=\'#d62728\', '
    b'linestyle=\'-.\', linewidth=1.5, alpha=0.7)\n    ax1.axhline(y=tp2_short, '
    b'color=\'#8b0000\', linestyle=\'-\', linewidth=1.5, alpha=0.7)\n    '
    b'ax1.axhline(y=sl_short, color=\'#ff7f0e\', linestyle=\':\', '
    b'linewidth=1.5, alpha=0.7)\n    \n    x_pos = df.index[0]\n    '
    b'ax1.text(x_pos, tp2_long, f\' Long TP2: {format_price(tp2_long)}\', '
    b'color=\'#006400\', fontsize=9, fontweight=\'bold\', va=\'bottom\')\n    '
    b'ax1.text(x_pos, tp1_long, f\' Long TP1: {format_price(tp1_long)}\', '
    b'color=\'#2ca02c\', fontsize=9, fontweight=\'bold\', va=\'bottom\')\n    '
    b'ax1.text(x_pos, entry_long, f\' Long Entry: {format_price(entry_long)}\', '
    b'color=\'blue\', fontsize=9, fontweight=\'bold\', va=\'bottom\')\n    '
    b'ax1.text(x_pos, sl_long, f\' Long SL: {format_price(sl_long)}\', '
    b'color=\'#ff7f0e\', fontsize=9, fontweight=\'bold\', va=\'bottom\')\n    '
    b'\n    ax1.text(x_pos, entry_short, f\' Short Entry: '
    b'{format_price(entry_short)}\', color=\'purple\', fontsize=9, '
    b'fontweight=\'bold\', va=\'bottom\')\n    ax1.text(x_pos, tp1_short, f\' '
    b'Short TP1: {format_price(tp1_short)}\', color=\'#d62728\', fontsize=9, '
    b'fontweight=\'bold\', va=\'bottom\')\n    ax1.text(x_pos, tp2_short, f\' '
    b'Short TP2: {format_price(tp2_short)}\', color=\'#8b0000\', fontsize=9, '
    b'fontweight=\'bold\', va=\'bottom\')\n    ax1.text(x_pos, sl_short, f\' '
    b'Short SL: {format_price(sl_short)}\', color=\'#ff7f0e\', fontsize=9, '
    b'fontweight=\'bold\', va=\'bottom\')\n\n    ax1.set_title(f\'Institutional '
    b'Adaptive Chart ({timeframe.upper()}): {display_name}\', fontsize=13, '
    b'fontweight=\'bold\', pad=12)\n    ax1.set_ylabel(\'Harga (USD)\', '
    b'fontsize=10)\n    ax1.grid(True, linestyle=\'--\', alpha=0.3)\n\n    '
    b'ax2.bar(x=df.index, height=df[\'Vol\'], color=colors, width=0.35, '
    b'alpha=0.8)\n    ax2.set_ylabel(\'Volume\', fontsize=10)\n    ax2.grid(True, '
    b'linestyle=\'--\', alpha=0.3)\n    ax2.xaxis.set_major_formatter('
    b'mdates.DateFormatter(\'%d %b\'))\n    plt.xticks(rotation=30, ha=\'right\', '
    b'fontsize=9)\n    \n    plt.tight_layout(pad=1.0)\n    \n    buf = '
    b'io.BytesIO()\n    plt.savefig(buf, format=\'png\', dpi=100, '
    b'bbox_inches=\'tight\')\n    buf.seek(0)\n    plt.close()\n    return buf\n'
    b'\ndef fetch_latest_news(symbol_query):\n    try:\n        clean_sym = '
    b'symbol_query.replace("b", "").upper()\n        url = '
    b'f"https://api.marketaux.com/v1/news/all?symbols={clean_sym}&filter_entities=true&limit=2&api_token={NEWS_API_KEY}"\n'
    b'        res = requests.get(url, timeout=5)\n        if res.status_code == '
    b'200:\n            articles = res.json().get("data", [])\n            if '
    b'articles:\n                news_text = "<b>Berita Terbaru:</b>\\n"\n      '
    b'          for art in articles[:2]:\n                    title = '
    b'art.get("title", "Tanpa Judul")\n                    link = art.get("url"'
    b', "#")\n                    news_text += f"â€¢ <a href=\'{link}\'>{title}</a>'
    b'\\n"\n                return news_text\n    except Exception as e:\n    '
    b'    logging.error(f"Gagal memuat berita: {e}")\n    return "<i>Berita '
    b'terbaru belum tersedia.</i>"\n\ndef '
    b'calculate_analysis_and_format_report(df, display_name, timeframe, '
    b'raw_symbol):\n    try:\n        if len(df) < 50:\n            return "âš ï¸ '
    b'Data historis tidak mencukupi untuk melakukan kalkulasi indikator.", 0, '
    b'0, 0, 0, 0, 0, 0, 0\n\n        current_price = float(df[\'Close\'].iloc[-1]'
    b')\n        prev_close = float(df[\'Close\'].iloc[-2]) if len(df) > 1 else '
    b'current_price\n        change = current_price - prev_close\n        '
    b'change_pct = (change / prev_close) * 100 if prev_close != 0 else 0\n    '
    b'    \n        if timeframe == \'6h\':\n            swing_window = 15\n    '
    b'        atr_multiplier = 1.6\n            risk_tp1 = 1.5\n            '
    b'risk_tp2 = 2.5\n        elif timeframe == \'1d\':\n            '
    b'swing_window = 25\n            atr_multiplier = 2.2\n            risk_tp1 '
    b'= 2.0\n            risk_tp2 = 3.5\n        else:\n            '
    b'swing_window = 20\n            atr_multiplier = 1.8\n            risk_tp1 '
    b'= 1.6\n            risk_tp2 = 2.8\n\n        delta = df[\'Close\'].diff()'
    b'\n        gain = (delta.where(delta > 0, 0)).rolling(14).mean()\n        '
    b'loss = (-delta.where(delta < 0, 0)).rolling(14).mean()\n        rsi_series '
    b'= 100 - (100 / (1 + (gain / loss)))\n        rsi = '
    b'float(rsi_series.iloc[-1])\n        \n        price_lower_low = '
    b'df[\'Low\'].iloc[-1] < df[\'Low\'].iloc[-5]\n        rsi_higher_low = '
    b'rsi_series.iloc[-1] > rsi_series.iloc[-5]\n        bullish_divergence = '
    b'price_lower_low and rsi_higher_low\n\n        price_higher_high = '
    b'df[\'High\'].iloc[-1] > df[\'High\'].iloc[-5]\n        rsi_lower_high = '
    b'rsi_series.iloc[-1] < rsi_series.iloc[-5]\n        bearish_divergence = '
    b'price_higher_high and rsi_lower_high\n\n        if rsi >= 70:\n           '
    b' rsi_status = "OVERBOUGHT (Jenuh Beli)"\n        elif rsi <= 30:\n        '
    b'    rsi_status = "OVERSOLD (Jenuh Jual)"\n        else:\n            '
    b'rsi_status = "NETRAL"\n\n        if bullish_divergence:\n            '
    b'rsi_status += " | Bullish Divergence"\n        elif bearish_divergence:\n'
    b'            rsi_status += " | Bearish Divergence"\n\n        ema_20 = '
    b'float(df[\'Close\'].ewm(span=20, adjust=False).mean().iloc[-1])\n        '
    b'ema_50 = float(df[\'Close\'].ewm(span=50, adjust=False).mean().iloc[-1])'
    b'\n        trend_bias = "Bullish" if current_price > ema_20 > ema_50 else '
    b'("Bearish" if current_price < ema_20 < ema_50 else "Sideways")\n\n        '
    b'if current_price > ema_20 > ema_50 and rsi < 70:\n            '
    b'market_status = "Strong Bullish Accumulation"\n        elif current_price '
    b'< ema_20 < ema_50 and rsi > 30:\n            market_status = "Strong '
    b'Bearish Distribution"\n        elif rsi >= 70:\n            market_status '
    b'= "Overbought Zone"\n        elif rsi <= 30:\n            market_status = '
    b'"Oversold Zone"\n        else:\n            market_status = "Neutral '
    b'Consolidation"\n\n        true_range = pd.concat([df[\'High\'] - '
    b'df[\'Low\'], (df[\'High\'] - df[\'Close\'].shift()).abs(), (df[\'Low\'] '
    b'- df[\'Close\'].shift()).abs()], axis=1).max(axis=1)\n        atr_14 = '
    b'float(true_range.rolling(14).mean().iloc[-1]) or (current_price * '
    b'0.015)\n\n        sma_20 = df[\'Close\'].rolling(window=20).mean()\n       '
    b' std_20 = df[\'Close\'].rolling(window=20).std()\n        lower_band = '
    b'float((sma_20 - (std_20 * 2)).iloc[-1])\n        upper_band = '
    b'float((sma_20 + (std_20 * 2)).iloc[-1])\n\n        swing_low = '
    b'float(df[\'Low\'].tail(swing_window).min())\n        swing_high = '
    b'float(df[\'High\'].tail(swing_window).max())\n\n        entry_long = '
    b'round(max(swing_low, min(current_price, ema_20, lower_band if not '
    b'math.isnan(lower_band) else current_price)), 4)\n        sl_long = '
    b'round(entry_long - (atr_14 * atr_multiplier), 4)\n        risk_long = '
    b'entry_long - sl_long\n        tp1_long = round(entry_long + (risk_long * '
    b'risk_tp1), 4)\n        tp2_long = round(entry_long + (risk_long * '
    b'risk_tp2), 4)\n        reason_long = f"Adaptive Swing Low '
    b'({format_price(swing_low)}), EMA 20, Bollinger Lower & ATR '
    b'{timeframe.upper()}."\n        if bullish_divergence:\n            '
    b'reason_long += " Bullish Divergence Confirmed."\n\n        entry_short = '
    b'round(min(swing_high, max(current_price, ema_20, upper_band if not '
    b'math.isnan(upper_band) else current_price)), 4)\n        sl_short = '
    b'round(entry_short + (atr_14 * atr_multiplier), 4)\n        risk_short = '
    b'sl_short - entry_short\n        tp1_short = round(max(0.00000001, '
    b'entry_short - (risk_short * risk_tp1)), 4)\n        tp2_short = '
    b'round(max(0.00000001, entry_short - (risk_short * risk_tp2)), 4)\n        '
    b'reason_short = f"Adaptive Swing High ({format_price(swing_high)}), EMA '
    b'20, Bollinger Upper & ATR {timeframe.upper()}."\n        if '
    b'bearish_divergence:\n            reason_short += " Bearish Divergence '
    b'Confirmed."\n\n        news_section = fetch_latest_news(raw_symbol)\n\n   '
    b'     sign = "+" if change >= 0 else ""\n        \n        report = (\n   '
    b'         f"<b>RISET INSTITUSIONAL (TF {timeframe.upper()}): '
    b'{display_name}</b>\\n\\n"\n            f"<b>Harga:</b> '
    b'{format_price(current_price)} ({sign}{change_pct:.2f}%)\\n"\n           '
    b' f"<b>Tren:</b> {trend_bias}\\n"\n            f"<b>RSI (14):</b> '
    b'{rsi:.2f}\\n"\n            f"<b>Kondisi:</b> <code>{rsi_status}</code>\\n"\n'
    b'            f"<b>Status Pasar:</b> <code>{market_status}</code>\\n\\n"\n '
    b'           f"<b>LONG SETUP</b>\\n"\n            f"â€¢ Entry: '
    b'<code>{format_price(entry_long)}</code>\\n"\n            f"â€¢ Stop Loss: '
    b'<code>{format_price(sl_long)}</code>\\n"\n            f"â€¢ TP1: '
    b'<code>{format_price(tp1_long)}</code>\\n"\n            f"â€¢ TP2: '
    b'<code>{format_price(tp2_long)}</code>\\n"\n            f"<i>Dasar: '
    b'{reason_long}</i>\\n\\n"\n            f"<b>SHORT SETUP</b>\\n"\n          '
    b'  f"â€¢ Entry: <code>{format_price(entry_short)}</code>\\n"\n            '
    b'f"â€¢ Stop Loss: <code>{format_price(sl_short)}</code>\\n"\n            '
    b'f"â€¢ TP1: <code>{format_price(tp1_short)}</code>\\n"\n            f"â€¢ TP2: '
    b'<code>{format_price(tp2_short)}</code>\\n"\n            f"<i>Dasar: '
    b'{reason_short}</i>\\n\\n"\n            f"{news_section}\\n"\n            '
    b'f"<i>Script dibuat oleh arifrfza (@vuxoz)</i>"\n        )\n        return '
    b'report, entry_long, entry_short, tp1_long, tp2_long, sl_long, sl_short, '
    b'tp1_short, tp2_short\n    except Exception as e:\n        logging.error('
    b'f"Error kalkulasi: {e}")\n        return "âš ï¸ Terjadi kesalahan saat '
    b'memproses kalkulasi.", 0, 0, 0, 0, 0, 0, 0, 0\n\nasync def '
    b'fetch_binance_data(symbol, timeframe):\n    try:\n        clean_symbol = '
    b'symbol.upper()\n        if clean_symbol in ["GOLD", "EMAS"]:\n           '
    b' clean_symbol = "PAXG"\n            \n        if not '
    b'clean_symbol.endswith("USDT"):\n            pair = f"{clean_symbol}USDT"'
    b'\n        else:\n            pair = clean_symbol\n\n        if timeframe == '
    b'\'6h\':\n            limit = 240\n        elif timeframe == \'1d\':\n    '
    b'        limit = 90\n        else:\n            timeframe = \'12h\'\n     '
    b'       limit = 150\n\n        url = '
    b'f"https://api.binance.com/api/v3/klines?symbol={pair}&interval={timeframe}&limit={limit}"\n'
    b'        res = requests.get(url, headers=REAL_BROWSER_HEADERS)\n        if '
    b'res.status_code != 200:\n            return None\n            \n        '
    b'data = res.json()\n        if not isinstance(data, list) or len(data) == '
    b'0:\n            return None\n\n        df = pd.DataFrame(data, '
    b'columns=[\'ot\', \'Open\', \'High\', \'Low\', \'Close\', \'Vol\', '
    b'\'ct\', \'qav\', \'nt\', \'tbb\', \'tbq\', \'ig\'])\n        df[[\'Open\', '
    b'\'High\', \'Low\', \'Close\', \'Vol\']] = df[[\'Open\', \'High\', '
    b'\'Low\', \'Close\', \'Vol\']].astype(float)\n        df.index = '
    b'pd.to_datetime(df[\'ot\'], unit=\'ms\')\n        return df\n    except '
    b'Exception as e:\n        logging.error(f"Binance fetch error: {e}")\n    '
    b'    return None\n\async def handle_request(update: Update, context: '
    b'ContextTypes.DEFAULT_TYPE):\n    if not context.args:\n        await '
    b'update.message.reply_text("âš ï¸ Format salah.\\n\\n<b>Tata Cara '
    b'Penggunaan:</b>\\nâ€¢ <code>/p btc 6h</code>\\nâ€¢ <code>/stock aaplb '
    b'1d</code>\\nâ€¢ Pilihan Timeframe: <code>6h</code>, <code>12h</code>, '
    b'<code>1d</code>", parse_mode="HTML")\n        return\n\n    arg = '
    b'context.args[0].upper()\n    symbol = "PAXG" if arg in ["GOLD", "EMAS"] '
    b'else arg\n    display_name = f"{symbol}/USDT"\n\n    timeframe = \'12h\''
    b'\n    if len(context.args) > 1:\n        tf_input = context.args[1].lower()'
    b'\n        if tf_input in [\'6h\', \'12h\', \'1d\']:\n            timeframe '
    b'= tf_input\n\n    status_msg = await update.message.reply_text(f"Melakukan '
    b'riset mendalam {display_name} (TF {timeframe.upper()})...")\n    df = '
    b'await fetch_binance_data(symbol, timeframe)\n    if df is None:\n        '
    b'await status_msg.edit_text(f"Simbol <b>{symbol}</b> tidak ditemukan di '
    b'Binance Spot Market.", parse_mode="HTML")\n        return\n\n    res_tuple '
    b'= calculate_analysis_and_format_report(df, display_name, timeframe, '
    b'symbol)\n    if res_tuple[1] == 0:\n        await '
    b'status_msg.edit_text(res_tuple[0])\n        return\n\n    chart_buf = '
    b'generate_chart(df, display_name, timeframe, *res_tuple[1:])\n    await '
    b'status_msg.delete()\n    await update.message.reply_photo(photo=chart_buf, '
    b'caption=res_tuple[0], parse_mode="HTML")\n\ndef main():\n    app = '
    b'ApplicationBuilder().token(TOKEN).build()\n    \n    app.add_handler('
    b'CommandHandler("start", start))\n    app.add_handler('
    b'CommandHandler("list", list_cmd))\n    app.add_handler('
    b'CommandHandler("p", handle_request))\n    app.add_handler('
    b'CommandHandler("stock", handle_request))\n    \n    print("Bot berjalan '
    b'dengan stabil dan siap digunakan...")\n    app.run_polling()\n\nif '
    b'__name__ == "__main__":\n    main()\n'
)

if __name__ == "__main__":
    exec(_enc_payload.decode('utf-8'))
